### PR TITLE
Optimise Code

### PR DESCRIPTION
**Pull request by FBI914-Admin**
Hey! I'm a student in 9th grade at RE, and I've helped optimize a bit of your code. I didn't make any significant changes yet, but I do have experience with HTML. I promise I did not cheat, but on that note, anyone who has a github account can find this repo, so I'd beware of that. The way you have set it up, to input a code at the end of the URL, I don't see any way around that, except via re-directs, for example, If I were to search https://ABCDE.com/123456 (Which would be the secret code), and this will redirect to https://ABCDE.com/ch1. I could do some research to help you find out more about how to do this with pure HTML and github hosting.

Best,
Jacob Katz

### CODE REVIEW

**Comment by FBI914-Admin** [comment]
I've found the way to do re-directs.  
```
<head>
<meta http-equiv = "HTTP Header" content = "LengthOfTimeForRedirect(0 for immediate); url = PutURLofRedirectHere" />
   </head>
```
I'm not sure exactly how you should use this to hide file names, but I hope this helps. 
Best,
Jacob Katz

**Comment by raidergames** [comment]
Ah you figured it out. I didn't think anyone at Ransom would have been able to :) I put it together pretty quickly a couple days ago and only thought about it this morning. I can just make the repo private right?

**Comment by raidergames** [comment]
Ah damn it I can't unless I have the pro account. I was earlier thinking about using a cutt.ly link (basically free bitly) but then thought I would have more control through github. Oh well hopefully no one tries to cheat.

**Comment by FBI914-Admin** [comment]
Yup! That's the idea. Don't worry. I won't share it. If you want, I can continue optimizing code. And I'll look into a way to hide the page names.

**Pull request merged**
